name: Nitrogen Tests
on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name : Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download Liquid Repository
        run: |
          git clone https://github.com/shrihari-prakash/liquid.git
          echo "Current Working Directory: $PWD"
          ls -l
          cd liquid/quickstart
          docker compose pull
          docker compose up -d
          docker ps -a
          cd ..
      - name: Install Dependencies
        run: |
          npm install
      #- name: Install dependencies
      #  run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
